# a) Usage of math methods: floor(), ceil(), sqrt(), isqrt(), gcd()

In [2]:
import math

x = 10.75
a = 25
b=15
print("Floor:", math.floor(x))

print("Ceil:", math.ceil(x))

print("Square Root:", math.sqrt(a))

print("Integer Square Root:", math.isqrt(a))

print("GCD of 25 and 15:", math.gcd(a, b))


Floor: 10
Ceil: 11
Square Root: 5.0
Integer Square Root: 5
GCD of 25 and 15: 5


# b) Usage of NumPy array attributes and methods

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Dimensions:", arr.ndim)

print("Shape:", arr.shape)

print("Size:", arr.size)

print("Sum:", arr.sum())

print("Mean:", arr.mean())

print("Sorted Array:\n", np.sort(arr))

print("Sine Values:\n", np.sin(arr))


Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Sum: 21
Mean: 3.5
Sorted Array:
 [[1 2 3]
 [4 5 6]]
Sine Values:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


# c) Usage of numpy.linalg or scipy.linalg for det(), eig()

In [4]:
import numpy as np
from numpy.linalg import det, eig

matrix = np.array([[4, 2], [3, 1]])


print("Determinant:", det(matrix))


eigenvalues, eigenvectors = eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Determinant: -2.0
Eigenvalues: [ 5.37228132 -0.37228132]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


# d) Convert 1D list to 2D, 3D using numpy.reshape()

In [5]:
import numpy as np

lst = [1, 2, 3, 4, 5, 6, 7, 8]

arr = np.array(lst)

arr_2d = arr.reshape(2, 4)
print("2D Array:\n", arr_2d)


arr_3d = arr.reshape(2, 2, 2)
print("3D Array:\n", arr_3d)

print("Zero Matrix:\n", np.zeros((2, 3)))
print("Identity Matrix:\n", np.eye(3))
print("One Matrix:\n", np.ones((3, 2)))


2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
One Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


# f) Find Determinant using scipy.linalg

In [7]:
import numpy as np
from scipy.linalg import det as sp_det

matrix = np.array([[5, 4], [6, 3]])
print("Determinant (using SciPy):", sp_det(matrix))


Determinant (using SciPy): -9.000000000000004


# g) find EigenValues and EigenVector using scipy.linalg

In [9]:
from scipy.linalg import eig as sp_eig
matrix = np.array([[2, -1], [1, 3]])
eigenvalues, eigenvectors = sp_eig(matrix)
print("Eigenvalues (SciPy):", eigenvalues)
print("Eigenvectors (SciPy):\n", eigenvectors)

Eigenvalues (SciPy): [2.5+0.8660254j 2.5-0.8660254j]
Eigenvectors (SciPy):
 [[ 0.35355339-0.61237244j  0.35355339+0.61237244j]
 [-0.70710678+0.j         -0.70710678-0.j        ]]
